### ISSUE TITLE
Incomplete extraction into Baselines

### ISSUE THREAD

**Issue by txtsd** [Pidgeot/python-lnp#192]
When a baseline does not exist, PyLNP downloads the appropriate zip to extract into the baselines folder.

However, I've found that it skips/fails to extract several important files like the `.txt` files in the init folder, even though they exist in the zip.

<details>
<summary>LNP/Baselines/df_47_05</summary>

```
λ exa -l --group-directories-first -R
drwxr-xr-x   - txtsd 28 Nov 20:13 data
drwxr-xr-x   - txtsd 28 Nov 20:13 raw
drwxr-xr-x   - txtsd 28 Nov 20:13 sdl
.rw-r--r-- 11k txtsd 28 Nov 20:13 readme.txt

./data:
drwxr-xr-x   - txtsd 28 Nov 20:13 announcement
drwxr-xr-x   - txtsd 28 Nov 20:13 art
drwxr-xr-x   - txtsd 28 Nov 20:13 dipscript
drwxr-xr-x   - txtsd 28 Nov 20:13 help
drwxr-xr-x   - txtsd 28 Nov 20:13 init
drwxr-xr-x   - txtsd 28 Nov 20:13 initial_movies
drwxr-xr-x   - txtsd 28 Nov 20:13 movies
drwxr-xr-x   - txtsd 28 Nov 20:13 sound
drwxr-xr-x   - txtsd 28 Nov 20:13 speech
.rw-r--r-- 418 txtsd 28 Nov 20:13 readme.txt

./data/announcement:

./data/art:
.rw-r--r--  74k txtsd 28 Nov 20:13 curses_640x300.bmp
.rw-r--r-- 1.6k txtsd 28 Nov 20:13 curses_640x300.png
.rw-r--r--  92k txtsd 28 Nov 20:13 curses_800x600.bmp
.rw-r--r-- 2.4k txtsd 28 Nov 20:13 curses_800x600.png
.rw-r--r-- 197k txtsd 28 Nov 20:13 curses_square_16x16.bmp
.rw-r--r-- 2.5k txtsd 28 Nov 20:13 curses_square_16x16.png
.rw-r--r-- 622k txtsd 28 Nov 20:13 font.ttf
.rw-r--r-- 4.8k txtsd 28 Nov 20:13 font license.txt
.rw-r--r-- 3.1k txtsd 28 Nov 20:13 mouse.bmp
.rw-r--r--  249 txtsd 28 Nov 20:13 mouse.png

./data/dipscript:
drwxr-xr-x - txtsd 28 Nov 20:13 text

./data/dipscript/text:

./data/help:

./data/init:
drwxr-xr-x - txtsd 28 Nov 20:13 macros

./data/init/macros:

./data/initial_movies:

./data/movies:

./data/sound:

./data/speech:
.rw-r--r-- 114 txtsd 28 Nov 20:13 ab_specific_hf_seeker.txt
.rw-r--r-- 106 txtsd 28 Nov 20:13 animal_slayer.txt
.rw-r--r-- 177 txtsd 28 Nov 20:13 arch_info_justification.txt
.rw-r--r--  21 txtsd 28 Nov 20:13 child_age_proclamation.txt
.rw-r--r--  27 txtsd 28 Nov 20:13 current_profession_no_year.txt
.rw-r--r--  59 txtsd 28 Nov 20:13 current_profession_year.txt
.rw-r--r--  42 txtsd 28 Nov 20:13 curse.txt
.rw-r--r-- 374 txtsd 28 Nov 20:13 dwarf.txt
.rw-r--r-- 276 txtsd 28 Nov 20:13 elf.txt
.rw-r--r--  67 txtsd 28 Nov 20:13 family_relationship_additional.txt
.rw-r--r--  68 txtsd 28 Nov 20:13 family_relationship_additional_dead.txt
.rw-r--r--  78 txtsd 28 Nov 20:13 family_relationship_no_spec.txt
.rw-r--r--  77 txtsd 28 Nov 20:13 family_relationship_no_spec_dead.txt
.rw-r--r--  71 txtsd 28 Nov 20:13 family_relationship_spec.txt
.rw-r--r--  72 txtsd 28 Nov 20:13 family_relationship_spec_dead.txt
.rw-r--r-- 343 txtsd 28 Nov 20:13 general.txt
.rw-r--r-- 354 txtsd 28 Nov 20:13 goodbye_worship_1.txt
.rw-r--r-- 197 txtsd 28 Nov 20:13 goodbye_worship_2.txt
.rw-r--r-- 640 txtsd 28 Nov 20:13 goodbye_worship_3.txt
.rw-r--r--  44 txtsd 28 Nov 20:13 greet.txt
.rw-r--r--  46 txtsd 28 Nov 20:13 greet_baby.txt
.rw-r--r--  37 txtsd 28 Nov 20:13 greet_reply.txt
.rw-r--r-- 104 txtsd 28 Nov 20:13 greet_reply_after_hero.txt
.rw-r--r--  51 txtsd 28 Nov 20:13 greet_reply_diff_language.txt
.rw-r--r-- 316 txtsd 28 Nov 20:13 greet_reply_unusual_first.txt
.rw-r--r-- 298 txtsd 28 Nov 20:13 greet_worship.txt
.rw-r--r--  13 txtsd 28 Nov 20:13 guard_profession.txt
.rw-r--r--  24 txtsd 28 Nov 20:13 guard_warning.txt
.rw-r--r--  78 txtsd 28 Nov 20:13 hist_fig_slayer.txt
.rw-r--r--  50 txtsd 28 Nov 20:13 hunting_profession.txt
.rw-r--r--  90 txtsd 28 Nov 20:13 hunting_profession_year.txt
.rw-r--r--  38 txtsd 28 Nov 20:13 justification_antithetical.txt
.rw-r--r--  27 txtsd 28 Nov 20:13 justification_experience.txt
.rw-r--r--  21 txtsd 28 Nov 20:13 justification_proximity.txt
.rw-r--r--  17 txtsd 28 Nov 20:13 justification_reminder.txt
.rw-r--r--  40 txtsd 28 Nov 20:13 justification_representation.txt
.rw-r--r--  87 txtsd 28 Nov 20:13 lair_hunter_minotaur.txt
.rw-r--r--  84 txtsd 28 Nov 20:13 mercenary_profession.txt
.rw-r--r-- 124 txtsd 28 Nov 20:13 mercenary_profession_year.txt
.rw-r--r--  28 txtsd 28 Nov 20:13 no_family.txt
.rw-r--r-- 102 txtsd 28 Nov 20:13 past_hunting_profession.txt
.rw-r--r-- 160 txtsd 28 Nov 20:13 past_mercenary_profession.txt
.rw-r--r--  33 txtsd 28 Nov 20:13 past_profession_no_year.txt
.rw-r--r--  73 txtsd 28 Nov 20:13 past_profession_year.txt
.rw-r--r-- 107 txtsd 28 Nov 20:13 past_snatcher_profession.txt
.rw-r--r--  90 txtsd 28 Nov 20:13 past_thief_profession.txt
.rw-r--r--  83 txtsd 28 Nov 20:13 past_wandering_profession.txt
.rw-r--r-- 208 txtsd 28 Nov 20:13 positive.txt
.rw-r--r-- 114 txtsd 28 Nov 20:13 same_site_ab_specific_hf_seeker.txt
.rw-r--r--  72 txtsd 28 Nov 20:13 same_site_specific_hf_seeker.txt
.rw-r--r--  72 txtsd 28 Nov 20:13 site_specific_hf_seeker.txt
.rw-r--r-- 122 txtsd 28 Nov 20:13 slayer.txt
.rw-r--r--  73 txtsd 28 Nov 20:13 snatcher_profession.txt
.rw-r--r-- 122 txtsd 28 Nov 20:13 snatcher_profession_year.txt
.rw-r--r--  15 txtsd 28 Nov 20:13 soldier_profession.txt
.rw-r--r--  50 txtsd 28 Nov 20:13 task_recommendation.txt
.rw-r--r--  71 txtsd 28 Nov 20:13 temple_already_member.txt
.rw-r--r-- 454 txtsd 28 Nov 20:13 temple_become_member.txt
.rw-r--r--  67 txtsd 28 Nov 20:13 thief_profession.txt
.rw-r--r-- 129 txtsd 28 Nov 20:13 thief_profession_year.txt
.rw-r--r--  15 txtsd 28 Nov 20:13 threat.txt
.rw-r--r--  84 txtsd 28 Nov 20:13 unknown_hf_seeker.txt
.rw-r--r--  36 txtsd 28 Nov 20:13 wandering_profession.txt
.rw-r--r--  76 txtsd 28 Nov 20:13 wandering_profession_year.txt

./raw:
drwxr-xr-x   - txtsd 28 Nov 20:13 graphics
drwxr-xr-x   - txtsd 28 Nov 20:13 interaction examples
drwxr-xr-x   - txtsd 28 Nov 20:13 objects
.rw-r--r-- 414 txtsd 28 Nov 20:13 readme.txt

./raw/graphics:
drwxr-xr-x    - txtsd 28 Nov 20:13 example
.rw-r--r-- 2.7k txtsd 28 Nov 20:13 graphics_example.txt

./raw/graphics/example:
.rw-r--r-- 2.4k txtsd 28 Nov 20:13 dwarves.bmp

./raw/interaction examples:
.rw-r--r-- 1.3k txtsd 28 Nov 20:13 example - bogeyman transformation.txt
.rw-r--r-- 4.6k txtsd 28 Nov 20:13 example - shrine effects.txt
.rw-r--r-- 3.0k txtsd 28 Nov 20:13 interaction_disturbance.txt
.rw-r--r-- 1.6k txtsd 28 Nov 20:13 interaction_region.txt
.rw-r--r-- 5.3k txtsd 28 Nov 20:13 interaction_secret.txt
.rw-r--r--  833 txtsd 28 Nov 20:13 interaction_underground_special.txt
.rw-r--r-- 1.8k txtsd 28 Nov 20:13 interaction_vampire.txt
.rw-r--r-- 1.6k txtsd 28 Nov 20:13 interaction_werebeast.txt

./raw/objects:
drwxr-xr-x    - txtsd 28 Nov 20:13 examples and notes
drwxr-xr-x    - txtsd 28 Nov 20:13 text
.rw-r--r--  23k txtsd 28 Nov 20:13 b_detail_plan_default.txt
.rw-r--r--  79k txtsd 28 Nov 20:13 body_default.txt
.rw-r--r--  24k txtsd 28 Nov 20:13 body_rcp.txt
.rw-r--r-- 1.4k txtsd 28 Nov 20:13 building_custom.txt
.rw-r--r--  26k txtsd 28 Nov 20:13 c_variation_default.txt
.rw-r--r-- 4.2k txtsd 28 Nov 20:13 creature_amphibians.txt
.rw-r--r-- 2.2k txtsd 28 Nov 20:13 creature_annelids.txt
.rw-r--r--  67k txtsd 28 Nov 20:13 creature_birds.txt
.rw-r--r-- 178k txtsd 28 Nov 20:13 creature_birds_new.txt
.rw-r--r--  57k txtsd 28 Nov 20:13 creature_bug_slug_new.txt
.rw-r--r--  18k txtsd 28 Nov 20:13 creature_desert_new.txt
.rw-r--r-- 112k txtsd 28 Nov 20:13 creature_domestic.txt
.rw-r--r--  829 txtsd 28 Nov 20:13 creature_equipment.txt
.rw-r--r--  736 txtsd 28 Nov 20:13 creature_fanciful.txt
.rw-r--r--  35k txtsd 28 Nov 20:13 creature_insects.txt
.rw-r--r--  32k txtsd 28 Nov 20:13 creature_large_mountain.txt
.rw-r--r-- 104k txtsd 28 Nov 20:13 creature_large_ocean.txt
.rw-r--r--  25k txtsd 28 Nov 20:13 creature_large_riverlake.txt
.rw-r--r-- 103k txtsd 28 Nov 20:13 creature_large_temperate.txt
.rw-r--r-- 158k txtsd 28 Nov 20:13 creature_large_tropical.txt
.rw-r--r--  18k txtsd 28 Nov 20:13 creature_large_tundra.txt
.rw-r--r--  12k txtsd 28 Nov 20:13 creature_mountain_new.txt
.rw-r--r--  96k txtsd 28 Nov 20:13 creature_next_underground.txt
.rw-r--r--  48k txtsd 28 Nov 20:13 creature_ocean_new.txt
.rw-r--r--  23k txtsd 28 Nov 20:13 creature_other.txt
.rw-r--r--  26k txtsd 28 Nov 20:13 creature_reptiles.txt
.rw-r--r--  44k txtsd 28 Nov 20:13 creature_riverlakepool_new.txt
.rw-r--r--  18k txtsd 28 Nov 20:13 creature_small_mammal_new.txt
.rw-r--r--  22k txtsd 28 Nov 20:13 creature_small_mammals.txt
.rw-r--r--  55k txtsd 28 Nov 20:13 creature_small_ocean.txt
.rw-r--r--  29k txtsd 28 Nov 20:13 creature_small_riverlake.txt
.rw-r--r-- 237k txtsd 28 Nov 20:13 creature_standard.txt
.rw-r--r-- 102k txtsd 28 Nov 20:13 creature_subterranean.txt
.rw-r--r-- 127k txtsd 28 Nov 20:13 creature_temperate_new.txt
.rw-r--r-- 120k txtsd 28 Nov 20:13 creature_tropical_new.txt
.rw-r--r--  12k txtsd 28 Nov 20:13 creature_tundra_taiga_new.txt
.rw-r--r-- 8.5k txtsd 28 Nov 20:13 descriptor_color_standard.txt
.rw-r--r--  13k txtsd 28 Nov 20:13 descriptor_pattern_iris_eye.txt
.rw-r--r--  11k txtsd 28 Nov 20:13 descriptor_pattern_pupil_eye.txt
.rw-r--r-- 1.9k txtsd 28 Nov 20:13 descriptor_pattern_special.txt
.rw-r--r-- 4.7k txtsd 28 Nov 20:13 descriptor_shape_standard.txt
.rw-r--r--  57k txtsd 28 Nov 20:13 entity_default.txt
.rw-r--r--  29k txtsd 28 Nov 20:13 inorganic_metal.txt
.rw-r--r-- 2.9k txtsd 28 Nov 20:13 inorganic_other.txt
.rw-r--r--  43k txtsd 28 Nov 20:13 inorganic_stone_gem.txt
.rw-r--r-- 6.8k txtsd 28 Nov 20:13 inorganic_stone_layer.txt
.rw-r--r--  24k txtsd 28 Nov 20:13 inorganic_stone_mineral.txt
.rw-r--r-- 5.1k txtsd 28 Nov 20:13 inorganic_stone_soil.txt
.rw-r--r-- 1.8k txtsd 28 Nov 20:13 interaction_standard.txt
.rw-r--r--  513 txtsd 28 Nov 20:13 item_ammo.txt
.rw-r--r-- 2.7k txtsd 28 Nov 20:13 item_armor.txt
.rw-r--r--  198 txtsd 28 Nov 20:13 item_food.txt
.rw-r--r--  658 txtsd 28 Nov 20:13 item_gloves.txt
.rw-r--r-- 1.7k txtsd 28 Nov 20:13 item_helm.txt
.rw-r--r-- 2.2k txtsd 28 Nov 20:13 item_pants.txt
.rw-r--r--  279 txtsd 28 Nov 20:13 item_shield.txt
.rw-r--r-- 1.3k txtsd 28 Nov 20:13 item_shoes.txt
.rw-r--r--  132 txtsd 28 Nov 20:13 item_siegeammo.txt
.rw-r--r-- 7.2k txtsd 28 Nov 20:13 item_tool.txt
.rw-r--r--  380 txtsd 28 Nov 20:13 item_toy.txt
.rw-r--r-- 1.2k txtsd 28 Nov 20:13 item_trapcomp.txt
.rw-r--r-- 8.9k txtsd 28 Nov 20:13 item_weapon.txt
.rw-r--r--  53k txtsd 28 Nov 20:13 language_DWARF.txt
.rw-r--r--  53k txtsd 28 Nov 20:13 language_ELF.txt
.rw-r--r--  52k txtsd 28 Nov 20:13 language_GOBLIN.txt
.rw-r--r--  52k txtsd 28 Nov 20:13 language_HUMAN.txt
.rw-r--r--  59k txtsd 28 Nov 20:13 language_SYM.txt
.rw-r--r-- 406k txtsd 28 Nov 20:13 language_words.txt
.rw-r--r--  88k txtsd 28 Nov 20:13 material_template_default.txt
.rw-r--r--  57k txtsd 28 Nov 20:13 plant_crops.txt
.rw-r--r--  89k txtsd 28 Nov 20:13 plant_garden.txt
.rw-r--r--  17k txtsd 28 Nov 20:13 plant_grasses.txt
.rw-r--r-- 102k txtsd 28 Nov 20:13 plant_new_trees.txt
.rw-r--r--  80k txtsd 28 Nov 20:13 plant_standard.txt
.rw-r--r-- 8.9k txtsd 28 Nov 20:13 reaction_adv_carpenter.txt
.rw-r--r--  19k txtsd 28 Nov 20:13 reaction_other.txt
.rw-r--r-- 6.4k txtsd 28 Nov 20:13 reaction_smelter.txt
.rw-r--r-- 9.1k txtsd 28 Nov 20:13 tissue_template_default.txt

./raw/objects/examples and notes:
.rw-r--r-- 3.5k txtsd 28 Nov 20:13 gaits.txt
.rw-r--r-- 5.4k txtsd 28 Nov 20:13 item_instrument_example.txt
.rw-r--r-- 1.5k txtsd 28 Nov 20:13 reaction_instrument_example.txt

./raw/objects/text:
.rw-r--r--  381 txtsd 28 Nov 20:13 book_art.txt
.rw-r--r-- 3.5k txtsd 28 Nov 20:13 book_instruction.txt
.rw-r--r--  210 txtsd 28 Nov 20:13 secret_death.txt

./sdl:

```

</details>

This causes loading keybinds to fail like so:

```
λ python launch.py
INFO: Registering path root as .
INFO: Registering path lnp as ./LNP
INFO: Registering path keybinds as ./LNP/Keybinds
INFO: Registering path graphics as ./LNP/Graphics
INFO: Registering path utilities as ./LNP/Utilities
INFO: Registering path colors as ./LNP/Colors
INFO: Registering path embarks as ./LNP/Embarks
INFO: Registering path tilesets as ./LNP/Tilesets
INFO: Registering path baselines as ./LNP/Baselines
INFO: Registering path mods as ./LNP/Mods
INFO: Registering path df as ./Dwarf Fortress df_47_05_linux
INFO: Registering path data as ./Dwarf Fortress df_47_05_linux/data
INFO: Registering path init as ./Dwarf Fortress df_47_05_linux/data/init
INFO: Registering path save as ./Dwarf Fortress df_47_05_linux/data/save
INFO: Registering path extras as ./LNP/Extras
INFO: Registering path defaults as ./LNP/Defaults
INFO: Registering path dfhack_config as ./Dwarf Fortress df_47_05_linux/dfhack-config/init
WARNING: Field PRIESTHOOD_UNIT_COUNTS seems to be missing from file ./Dwarf Fortress df_47_05_linux/data/init/d_init.txt!
WARNING: Field GUILD_UNIT_COUNTS seems to be missing from file ./Dwarf Fortress df_47_05_linux/data/init/d_init.txt!
WARNING: Can't load or change keybinds with missing baseline!
INFO: Read installed graphics (Phoebus) from log
INFO: Extracting archives in baselines: ['./LNP/Baselines/df_47_05_win_s.zip']
INFO: Simplifying baselines: df_47_05
INFO: Loading keybinds:  ./LNP/Keybinds/Laptop with mouse.txt
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/txtsd/.pyenv/versions/3.7.14/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/txtsd/git/python-lnp/tkgui/options.py", line 129, in <lambda>
    self.keybinding_files.bind(seq, lambda e: self.load_keybinds())
  File "/home/txtsd/git/python-lnp/tkgui/options.py", line 283, in load_keybinds
    keybinds.load_keybinds(listbox.get(items[0]))
  File "/home/txtsd/git/python-lnp/core/keybinds.py", line 99, in load_keybinds
    _sdl_write_binds(target, _sdl_get_binds(filename), expanded=True)
  File "/home/txtsd/git/python-lnp/core/keybinds.py", line 51, in _sdl_get_binds
    van = _get_vanilla_binds()
  File "/home/txtsd/git/python-lnp/core/keybinds.py", line 81, in _get_vanilla_binds
    return _sdl_get_binds(vanfile, compressed=False)
  File "/home/txtsd/git/python-lnp/core/keybinds.py", line 41, in _sdl_get_binds
    with open(filename, encoding='cp437') as f:
FileNotFoundError: [Errno 2] No such file or directory: './LNP/Baselines/df_47_05/data/init/interface.txt'
```

This happens on master with Python 3.7.x as well as 3.10.x

**Comment by txtsd** [comment]
Seems like #163 is basically this same problem.
